name: Add-on Validations

on:
  push:
    branches: [ master, main, dev ]

  pull_request:
    branches: [ master, main, dev ]

jobs:

  addon-validations:

    name: Add-on Validations
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout Add-on
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install isort
          python -m pip install pylint
          python -m pip install simpleeval
          python -m pip install unidecode
          python -m pip install git+https://github.com/xbmc/addon-check.git

      - name: Kodi Add-on Checker
        id: kodi-addon-checker-matrix
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=matrix

      - name: Pylint
        id: pylint
        run: |
          cp -t ${HOME} .pylintrc
          pylint resources/lib/
        working-directory: ${{ github.event.repository.name }}

      - name: isort
        id: isort
        run: |
          isort --force-single-line-imports . --diff
        working-directory: ${{ github.event.repository.name }}
